### ISSUE TITLE
Refine individual project pages

### ISSUE THREAD

**Issue by erreeves** [sfcta/MyStreetSF-2.0#37]

**Comment by billyc** [comment]
- get rid of pennies
- social buttons
- get back to map
- final list from Anna of fields
- Make prettier

**Comment by erreeves** [comment]
Change "Current Phase" label to "Phase(s)"
Change "Percent Complete of Funded Phase" label to "Percent Complete of Funded Phase(s)"
Change "Cost Estimate" label to "Total Project Cost"

Change order to match Excel Document for Detailed Project Information Area

Can we have orange headers all be equal length? (same as Brief Project Description)
[Proposed Project Page Layout.xlsx](https://github.com/sfcta/MyStreetSF-2.0/files/2178157/Proposed.Project.Page.Layout.xlsx)
