### ISSUE TITLE
Implement full-text search w/dropdown

### ISSUE THREAD

**Issue by billyc** [sfcta/MyStreetSF-2.0#4]
- Move full-text search to a bar on top of the map
- Auto-suggest dropdown should list matching projects, a la NYC map

**Comment by billyc** [comment]
Looks like the latest PostgREST 4.4 includes full text search
- http://rachbelaid.com/postgres-full-text-search-is-good-enough/
- So I need to upgrade the prospector-api VM and add a new full-text-search column

**Comment by joecastiglione** [comment]
Billy,

Thanks for pushing this forward.

Should I be seeing the interface?  Or just the text results of the query?

Joe

**Comment by billyc** [comment]
- Full-text search on project details now working
- Tag search now working

Still to do: address search. Gonna wait until we have some tags and project details in the database so we can "harden" that function first.
